# Generated by Django 3.2.6 on 2021-09-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docDate', models.DateField()),
                ('docType', models.CharField(default='?', max_length=4)),
                ('companyCode', models.CharField(default='?', max_length=4)),
                ('postDate', models.DateField(default='08/09/2021')),
                ('period', models.IntegerField(default='?')),
                ('currency', models.CharField(default='?', max_length=3)),
                ('reference', models.CharField(max_length=100)),
                ('docHeader', models.CharField(max_length=100)),
                ('partnerBArea', models.CharField(blank=True, max_length=100)),
                ('pstKey', models.CharField(max_length=2)),
                ('accountBottom', models.CharField(max_length=100)),
            ],
        ),
    ]
