# Generated by Django 3.2.6 on 2021-09-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('calculateTax', models.BooleanField(default=True)),
                ('busArea', models.CharField(max_length=4)),
                ('paytTerms', models.CharField(default='AR30', max_length=3)),
                ('percent1', models.IntegerField(default=30)),
                ('bLineDate', models.DateField(default='09/09/2021')),
                ('discAmt', models.IntegerField(blank=True)),
                ('discBase', models.IntegerField(blank=True)),
                ('invoiceRef1', models.CharField(blank=True, max_length=100)),
                ('pmtBlock', models.CharField(blank=True, max_length=2)),
                ('pmtMethod', models.CharField(blank=True, max_length=2)),
                ('assignmentPg3', models.CharField(max_length=200)),
                ('textPg3', models.CharField(max_length=200)),
                ('pstKey', models.CharField(max_length=2)),
                ('accountBottom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='secondpage',
            name='companyCode',
            field=models.CharField(blank=True, default='?', max_length=4),
        ),
        migrations.AlterField(
            model_name='secondpage',
            name='postDate',
            field=models.DateField(default='09/09/2021'),
        ),
    ]
