# Generated by Django 3.2.6 on 2021-09-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210909_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50)),
                ('companyCode', models.IntegerField()),
                ('secondPageEntry', models.ManyToManyField(to='main.SecondPage')),
            ],
        ),
    ]
