# Generated by Django 3.2.6 on 2021-09-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitentry',
            name='discAmt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debitentry',
            name='discBase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debitentry',
            name='paytTerms',
            field=models.CharField(default='AR30', max_length=4),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
