# Generated by Django 3.2.6 on 2021-09-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210910_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('trdgPartBA', models.CharField(blank=True, max_length=4)),
                ('docHeader', models.CharField(max_length=100)),
            ],
        ),
    ]
